---
- hosts: all

  become: true
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
  
    # Check if reboot is required
    # - name: check is system reboot is required
    #   become: true
    #   stat:
    #     path: /var/run/reboot-required
    #   register: reboot_required