---
- name: deploy uptime-kuma latest
  hosts: "{{ hosts }}"
  become: yes
  become_user: "{{ lookup('env','USER') }}"
  tasks:
  - name: create new volume
    community.docker.docker_volume:
      name: uptime-kuma
  - name: deploy uptime-kuma
    community.docker.docker_container:
      name: uptime-kuma
      image: "louislam/uptime-kuma:1"
      ports:
        - "3001:3001"
      volumes:
        - uptime-kuma:/app/data
      restart_policy: always
